name: .NET API Build

on:
  pull_request:
    paths:
      - 'alms.api/**'
      - '.github/workflows/dotnet-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      working-directory: ./alms.api
      run: dotnet restore
    
    - name: Build
      working-directory: ./alms.api
      run: dotnet build --no-restore
    
    - name: Test
      working-directory: ./alms.api
      run: dotnet test --no-build --verbosity normal